minimum_pre_commit_version: 2.9.2
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-ast
-   repo: https://github.com/python/black
    rev: 21.11b1
    hooks:
    -   id: black
        args: [--line-length=120]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        # Ignored Flake8 rules
        args: ['--ignore=E402,E501,F401,F811,W503']
-   repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
    -   id: codespell
        types_or: [python, rst]
        exclude: ^(pycraigslist/api.py|pycraigslist/filters.py)
-   repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.0
    hooks:
    -   id: absolufy-imports
